version: '3.1'

services:
  db:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_PASSWORD: Enigma45#
      POSTGRES_DB: db_ms_cadastro
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
